import argparse
from src import tokenizer

def train_tokenizer():
    """
    Train and save a BPE-like tokenizer from a text file using command-line arguments.

    The function reads the training text, creates a tokenization with the requested
    number of merge rules, saves the resulting vocabulary and rules to JSON, and
    prints the output file path.

    Command-line arguments
    ----------------------
    --num-merges : int, default=100
        Maximum number of BPE merge rules to learn.

    --tokenization-name : str or None, default=None
        Name of the output tokenization JSON file. If None, a timestamped file name
        is generated by the save function.

    --text-path : str, default="tiny_shakespare.txt"
        Path to the text file used to train the tokenizer.

    --save-dir : str or None, default=None
        Directory where the tokenization JSON file will be saved. If None, the
        default tokenizations folder is used.

    Returns
    -------
    None
        The function saves the trained tokenization to disk and prints its path.

    Notes
    -----
    This function is intended to be used as a command-line entry point.
    """
    parser = argparse.ArgumentParser()

    parser.add_argument("--num-merges", type=int, default=100)
    parser.add_argument("--tokenization-name",type=str, default=None)
    parser.add_argument("--text-path",type=str, default="tiny_shakespare.txt")
    parser.add_argument("--save-dir",type=str, default=None)

    args = parser.parse_args()

    num_merges = args.num_merges
    name = args.tokenization_name
    text_path = args.text_path
    save_dir = args.save_dir

    txt = open(text_path,mode="r",encoding="utf-8").read()

    print("Creating tokenization....")
    token_to_id, id_to_token, rules = tokenizer.create_bpe_tokenization(txt,num_merges)
    file_path = tokenizer.save_to_JSON(token_to_id,id_to_token,rules,name,save_dir)
    print("The tokenization has been created correctly: ",file_path)

if __name__ == "__main__":
    train_tokenizer()